name: Full CI process
on:
    workflow_dispatch:
    push:
        branches:
            - $default-branch
    pull_request:
        branches:
            - $default-branch

permissions: read-all

jobs:
    test:
        permissions:
          contents: read
        name: PHP ${{ matrix.php-versions }}
        runs-on: ubuntu-18.04
        strategy:
            fail-fast: false
            matrix:
                php-versions: ['7.2', '7.3', '7.4', '8.0']

        steps:
            # —— Setup Github actions 🐙 —————————————————————————————————————————————
            # https://github.com/actions/checkout (official)
            - name: Harden Runner
              uses: step-security/harden-runner@917f7d59f22e82a5ddcaef409923426fd7aa6327
            -
                name: Checkout
                uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5

            # https://github.com/shivammathur/setup-php (community)
            -
                name: Setup PHP, extensions and composer with shivammathur/setup-php
                uses: shivammathur/setup-php@3212f1feafd55735969bda7e73638a7577058e02
                with:
                    php-version: ${{ matrix.php-versions }}
                    extensions: mbstring, ctype, iconv, bcmath, filter, json
                    coverage: none
                env:
                    update: true

            # —— Composer 🧙‍️ —————————————————————————————————————————————————————————
            -
                name: Install Composer dependencies
                run: |
                    git config --global author.name Sebastiaan Stok
                    git config --global author.email s.stok@rollerscapes.net
                    git config --global user.name Sebastiaan Stok
                    git config --global user.email s.stok@rollerscapes.net

                    rm -f composer.lock
                    composer global require symfony/flex
                    composer install --no-progress --no-interaction --no-suggest --optimize-autoloader --ansi

            ## —— Tests ✅ ———————————————————————————————————————————————————————————
            -
                name: Run Tests
                run: |
                    make test
                    cp config.php.dist config.php
                    bin/hubkit.php self-diagnose
    lint:
        permissions:
          contents: read
        name: PHP-QA
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@917f7d59f22e82a5ddcaef409923426fd7aa6327
            -
                name: Checkout
                uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5

            # https://github.com/shivammathur/setup-php (community)
            -
                name: Setup PHP, extensions and composer with shivammathur/setup-php
                uses: shivammathur/setup-php@3212f1feafd55735969bda7e73638a7577058e02
                with:
                    php-version: '7.4'
                    extensions: mbstring, ctype, iconv, bcmath, filter, json
                    coverage: none

            # —— Composer 🧙‍️ —————————————————————————————————————————————————————————
            -
                name: Install Composer dependencies
                run: |
                    rm -f composer.lock
                    composer global require symfony/flex
                    composer install --no-progress --no-interaction --no-suggest --optimize-autoloader --ansi

            -
                name: Run PHP-QA
                run: |
                    make security-check cs-full phpstan
